(function(z){
'use strict';var m$=function(a){z.L.call(this);this.w(a)},q2a=function(a,b){this.user=a;this.quotes=b},r2a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},n$=function(a){return a.oA.best||null},o$=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.hb(b,function(a){return a.mb()},a);return z.ob(b).map(function(a){return new q2a(a[0].vc(),a)},a)},s2a=function(a,b,c,d){return(0,z.ud)(a.tt[b.name]||
[],function(a){return a.wd()==c&&a.ye()==d})},p$=function(){this.sF=1},q$=function(a){z.Wj.call(this);this.w(a)},t2a=function(a,b){return z.K(a,"slots",b)},u2a=function(a,b){return z.K(a,"requestContext",b)},r$=function(a){z.L.call(this);this.w(a)},s$=function(a){return z.I(a,"inResponseToMediaResource")},t$=function(a){return z.I(a,"mediumQuote")},v2a=function(a,b){a.lO=b;return a},u$=function(a,b){return n$(a)?z.kF(n$(a)).filter(function(a){return this.J2(a)==b},a):[]},w2a=function(a,b,c){c=c.Bx;
b=b.getAttribute("name").split(" ");var d=z.yb(b);a=(a.tt[c.name]||[]).filter(function(a){return d[a.Si()]});return a.length?z.pqa(a):null},x2a=function(a,b,c,d){b=s2a(a,b,c,d);return o$(a,b)},y2a=function(a,b){var c=0;(a.tt[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Oe())});return c},z2a=function(a){var b=z.HP(a.Yj.Qs,a.Yj.er(),a.Yl.Qs,a.Yl.er()).Ga().trim();0<a.Yj.er()&&(b="…"+b);var c=z.wH(a.yc,a.Yl.Qs);a.Yl.er()<c.Ga().length&&(b+="…");return b},A2a=function(a){var b=z.iE(a.bva),c=a.Yj.Qs,
d=c?b.indexOf(c):-1,e=(c=a.Yl.Qs)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.wH(a.yc,b[d]));b=z.Qa(c);a=z.Qx(c.indexOf(c[0]),a.Yj.er(),c.indexOf(b),a.Yl.er(),!1);return z.Rga(new z.Cx(z.Xr,z.Vva),c,a,!0)},B2a=function(a,b,c){var d=a.la.ka(z.zxa,{postId:b},{filter:c});return z.iH(a,d,function(){return this.Ab.Aj(d)})},C2a=function(a,b){z.kx(a,7);var c=new z.bx("",1,a.Ga());b.forEach(function(a){z.ix(c,z.Uw(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.Ega(c);for(var d=
z.Fga(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],q=0;q<g.length;q++){var r=g[q];k[z.I(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];q=e<b.length-1?b[e+1]:a.Ga().length;z.ix(a,z.Uw(g,q,l,Object.keys(k)))}}},D2a=function(a,b,c){b="";a.RCa?a=z.n("Top highlight"):(c=""+z.A(z.VR(z.D({U3:!0,uia:!c.useragent.isMobile},a),c)),1==a.Ai&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},v$=function(a,b){this.fi=a;this.Qoa=b;this.Ke=(this.Jk=b=z.dE(a.node,
b))&&b.getAttribute("name");this.$N=b?z.IA(a,b):-1},E2a=function(a,b,c){return(0,z.y)(z.vR(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},F2a=function(a,b,c){b='\x3cdiv\x3e\x3cdiv class\x3d"buttonSet u-inlineBlock"\x3e'+z.A(z.co({action:"quote",source:"quote_popover",icon:(0,z.O)(""+z.A(z.Vm())),j:(0,z.O)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),bc:!0,Zi:!0,Dda:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?
z.A(z.co({action:"quote-respond",source:"quote_popover",icon:(0,z.O)(""+z.A(z.mn())),j:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",bc:!0,wa:!0},c)):"")+(a.UT?z.A(z.co({action:"twitter",source:"quote_popover",icon:(0,z.O)(""+z.A(z.qn())),j:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",bc:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop14 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+D2a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},w$=function(a){z.Yr.call(this);var b=z.Zs();this.Yj=b&&new v$(z.zt(b,!0),a);this.Yl=b&&new v$(z.zt(b,!1),a)},x$=function(a){z.L.call(this);this.w(a)},y$=function(a,b){var c=new z.Kk(z.Wr(b)),c=new z.ge(c.ka(z.xwa)),d=new z.ge("https://www.facebook.com/v2.3/dialog/share");z.ke(d,z.Ge({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},G2a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},
H2a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.l.o5&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({e6:b},a),d=d||{},d=d.e6;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+
z.A(z.kq({title:(0,z.O)(""+z.A(z.Yo())),ZB:!0,Og:(0,z.O)(""+(c.supportsEdit&&d?z.bLa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.$Ka(z.D({Qe:b},a),c)+(b?z.aLa(a,c):"")+z.ZKa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},I2a=function(a){return(0,z.y)(z.A(z.Vo(String(a.content)))+" — "+z.A(z.KI(a))+" "+z.A(a.url))},J2a=function(a,b,c){return(0,z.vk)("https://"+z.Ei(c.textshotHost)+"/image")},K2a=function(a,b,c){return(0,z.vk)("https://twitter.com/"+z.Ei(c.currentUser.twitterScreenName)+"/status/"+
z.Ei(a.id))},L2a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},M2a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+z.A(z.Yp({user:a.user,ge:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';
var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.lm(z.D({name:"addCircled",size:"21px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.O)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.co({icon:d,isPrimary:!0,wa:!0,j:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.O)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.O)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.Zn({s:d,Td:!0,j:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.O)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},N2a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},O2a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.JGa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.P({tb:!0,href:a,s:(0,z.O)(""+e)},c));return(0,z.y)(d)},P2a=function(){var a=z.n("Tweet must be 140 characters or less.");return(0,z.y)(""+a)},z$=function(a,b,c){z.R.call(this);this.ue=a.get("quotes-data");var d=this.ue.Mo;d.subscribe("add",this.Nba,this);d.subscribe("remove",this.Nba,this);this.bb=b;this.Pd=b.Vl;this.dm=c;this.p9=[];this.Ia=a.get("app");this.Da=a.get("popover");this.la=a.get("route-builder");this.GX=a.get("global-event-bus");this.ova=a.get("progressive-media-loader")},
R2a=function(a,b,c,d){var e=Q2a(a,b);if(e){var g=a.bb.isPublished(),k=z.Jqa(a.bb);e.UT=g&&k;if(c=z.GH(z.AG(z.zG(z.BG(z.HH(z.CG(a.Da).fb(F2a,e),"top"),c),{hS:!0,Ix:!0,Fa:!0}),"popover--quoteAttributions"),d).pa())c.bo("deactivate",function(){this.Wo===b&&A$(this,null)},a),c.Hn().aa("quote",a.Opa.bind(a,c)).aa("quote-respond",a.Ppa.bind(a,c)).aa("twitter",a.Qpa.bind(a))}},Q2a=function(a,b){if("anon"==b.mb())return{isActive:!1,RCa:!0};var c=B$(a,b),d=b.wd();b=b.ye();a=x2a(a.ue,c,d,b);if(!a||!a.length)return null;
a=(0,z.Ab)(a,function(a){return a.user});c=(0,z.ud)(a,function(a){return a.userId!=z.fv().userId});return{isActive:(0,z.dd)(a,function(a){return a.userId==z.fv().userId}),social:c,Ai:a.length}},S2a=function(a,b){a=a.Pd.querySelectorAll('.markup--quote[name~\x3d"'+b.Si()+'"]');return z.Ya(a)},B$=function(a,b){b=b.jc()[0].name;return(b=z.Gw(a.Pd,b))?a.bb.Ri(b):null},T2a=function(a,b){var c=z.$s(b);return(c=z.sI(a.dm,c))?w2a(a.ue,b,c):null},A$=function(a,b){a.Wo!==b&&(a.Wo&&U2a(a,a.Wo,!1),b&&U2a(a,b,
!0),a.Wo=b)},U2a=function(a,b,c){S2a(a,b).map(function(a){z.xd(a,"is-targeted",c)})},C$=function(a,b){(b=V2a(a,b))&&z.qI(a.nk(),b)},V2a=function(a,b){var c=b.jc(),d=z.Gw(a.Pd,c[0].getName());a=z.Gw(a.Pd,z.Qa(c).getName());return z.HP(d,b.wd(),a,b.ye())},D$=function(a,b,c,d){a={postId:a.bb.La(),quoteId:b,source:d};z.OB(c?z.wqa:z.$ya,a)},W2a=function(a,b){z.hE(a,z.gE,z.Pb(b,z.Lb(!0)),void 0)},X2a=function(a,b,c){z.qa(a)||(a=a.toString());var d=window,e={scrollbars:!0,yFa:!0,toolbar:!1,location:!0,width:670,
height:690};z.wb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",yFa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.gs(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();
return d.open(a,b,c)},Y2a=function(a){var b=z.hA(z.Rra,{GDa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Fa(a)}),b.length&&z.td(a,b))},Z2a=function(a){if(!a)return"";var b=[],c=z.ub(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},E$=function(a){z.fB.call(this);this.yc=a.get("dom-model-converter");this.Jaa={};this.D$={};this.HZ={};this.ra=a;this.gn=a.get("request");this.la=a.get("route-builder");this.ya=a.get("model-store");this.kb=
"";this.jba=z.Or;this.m9=!1;this.xh=null},F$=function(a,b){var c=a.Jaa[b];c||(c=a.Jaa[b]=new z.fF,a.za("new_note_list",c,a));return c},$2a=function(a,b){if(!b)return!1;var c=b.Ga();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ia(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):!1},G$=function(a,b,c){var d=b.La(),e=b.wg(),g=F$(a,b.je()),k=g?g.indexOf(b):-1,l=b.cI();b.qy(c);
"HIDDEN"==c?a.ya.remove(b):b=z.bF(a.ya,b);var q=g?g.indexOf(b):-1;return{ul:a.gn.put(a.la.ka(z.Gwa,{postId:d,noteId:e}),{state:c}),mJ:function(){b.qy(l);-1==q&&(-1==k?g.add(b):z.hF(g,b,k))}}},H$=function(a,b,c,d,e,g){var k=z.I(a.pp(c,e),"replies"),l=z.Ra(k,function(a){return a.vx()==b}),q=k[l];"HIDDEN"==g&&z.Va(k,l);c=a.la.ka(z.Jwa,{postId:d,noteId:c,replyId:b});a=a.gn.put(c,{state:g});var r=z.Ra(k,function(a){return a.vx()==b});return{ul:a,mJ:function(){-1==r&&z.bb(k,l,0,q)}}},a3a=function(a,b,c){this.range=
a;this.anchor=b;this.$A=b.getAttribute("name");this.highlight=c},I$=function(a,b,c){z.R.call(this);this.PO=b;this.Zua=c;this.Na=a.get("screen");this.Xa=a.get("screen-request")},b3a=function(a,b){b=b.querySelectorAll(".js-trackedPostPromotion");null!=a.PO.postPageContext&&null!=a.PO.postPageContext.postId&&z.Ya(b).forEach(function(b){var d=a.PO.postPageContext.postId,e=b.getAttribute("data-post-id"),g=b.getAttribute("data-post-promotion-source");b=b.getAttribute("data-location-id");z.OB(z.Cza,{hostPostId:d,
targetPostId:e,promotionSource:g,locationId:b})})},c3a=function(){},d3a=function(a){this.ZN=a},J$=function(a,b){return b?z.Gw(a.ZN,b):null},e3a=function(a,b,c){W2a(a.ZN,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})},f3a=function(a,b){return z.vh(a.ZN,b)?a.ZN:null},K$=function(a,b,c,d,e){z.yY.call(this,a,b);this.$a(new z.PX(c));this.$a(new z.gZ(!1));this.$a(new z.iZ(a));this.$a(new z.zY);this.$a(new z.RZ(!1,!1));this.$a(new z.k_(d,!0));this.Zk=!0;this.cm=d;this.gn=a.get("request");this.Ba=
a.get("dialog");this.lZ=e;this.pa()},g3a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+a)},h3a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},i3a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},j3a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");
return(0,z.y)(""+a)},k3a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},l3a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},m3a=function(){var a=z.n("The reply has been deleted.");return(0,z.y)(""+a)},n3a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},o3a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},L$=function(a,b,c,d,e){K$.call(this,a,b,e||"Leave a note",400,d||null);this.kb=c;this.la=a.get("route-builder");this.tf=a.get("notes-data")},
M$=function(a,b,c,d,e,g){K$.call(this,a,b,"Leave a reply…",200,d);this.la=a.get("route-builder");this.tf=a.get("notes-data");this.kb=c;this.Jba=g||null;this.Ke=e},q3a=function(a,b,c){var d='\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.G6;b=a.notes.length||a.OT;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.lq({title:(0,z.O)(z.A(G2a())+" ("+z.A(a.quotes.length)+")"),df:!0},c)),k;k={Eha:a.quotes,mHa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';
if(!k.mHa)var q=z.n("Learn more"),l=l+z.A(z.lq({title:(0,z.O)(""+z.A(G2a())),df:!0,Og:(0,z.O)(""+z.A(z.jq({href:(0,z.M)(""+z.G((0,z.vk)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:(0,z.O)(""+q),Bb:!0},c)))},c));for(var q="list u-marginTop5 u-marginBottom15"+(k.Eha.length?"":" u-hide"),q=(0,z.O)(q),l=l+('\x3cul class\x3d"'+z.F(q)+'"\x3e'),q=k.Eha,r=q.length,u=0;u<r;u++){for(var v=q[u],C="",J=v.quotes,Q=J.length,N=0;N<Q;N++)C+=""+J[N].quoteId+(N!=Q-1?",":"");C=z.E(C);
l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(C)+'" data-quote-creator-id\x3d"'+z.F(v.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+z.A(z.Wp(z.D({user:v.user,Ue:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.G6?" is-withEditor":"")+'"\x3e'+z.A(z.lq({title:(0,z.O)(""+z.A(z.Yo())),df:!0},c)),a.G6&&c.supportsEdit&&c.isAuthenticated?
(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.vR(z.D({user:c.currentUser,isCollapsed:!0,XB:!0,type:"quoteResponses",Ku:(0,z.O)(""+z.A(z.fp()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+p3a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.OEa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=
c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.O)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+
'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.lm(z.D({name:"lock",size:"19px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.O)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={CGa:g,title:(0,z.O)(""+z.A(e)),df:!0,Og:(0,z.O)(b),j:"heading--privateNotes"};b=(0,z.y)(z.hq(z.D({rl:(0,z.O)(""+z.iq(b,c)),ADa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.OT?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=N$({note:g[k],post:a.post,LJ:a.LJ},0,c);a.OT?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.$n({action:"show-note-editor",text:(0,z.O)(""+z.A(a)),j:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.Xp({user:c.currentUser,ge:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.$n({action:"save-note",isPrimary:!0,j:"js-saveNoteButton",
text:(0,z.O)(""+z.A(k))},0,c))+z.A(z.$n({action:"hide-note-editor",text:(0,z.O)(""+z.A(o3a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.OC&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.co({ub:!0,Td:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.O)(""+z.A(z.rm())),title:(0,z.O)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.co({ub:!0,Td:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.O)(""+z.A(z.um())),title:(0,z.O)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},p3a=function(a,b,c){return(0,z.y)(z.A(z.eS({posts:a.responses,source:"quoteResponses",
JR:!0},0,c)))},N$=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var q=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),q=z.E(q),q='\x3cdiv class\x3d"privateNotes-item '+
z.F(q)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.Wp({user:a.note.author},c)):z.A(z.Up({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.oo({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.iga?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");q=
q+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.lj(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.zy(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.Nh(k,z.Th)?(0,z.y)(l,z.Rh(k)):l;d=""+(q+k+"\x3c/div\x3e"+(d?r3a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,q=0;q<g;q++)k=e[q],d+=N$({note:k,post:a.post,iga:a.note.author.userId==k.author.userId},0,c);e=d;a.LJ?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.Vp({user:c.currentUser,ge:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',q=z.n("Send"),q=(0,z.y)(""+q),g=g(d+z.A(z.$n({action:"save-reply",isPrimary:!0,text:(0,z.O)(""+z.A(q))},0,c))+z.A(z.$n({action:"hide-reply-editor",text:(0,z.O)(""+z.A(o3a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.LJ?(d=z.y,q=z.n("Reply"),q=(0,z.y)(""+q),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.$n({isPrimary:!0,action:"show-reply-editor",j:"privateNotes-prompt",text:(0,z.O)(""+z.A(q))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+r3a({note:a.note,isPrimary:!0,Tfa:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},r3a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.Tfa?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.Tfa?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.$n({actionValue:d,action:e,j:"privateNotes-delete js-deleteNote",text:(0,z.O)(""+a)},0,b)))},s3a=function(a,b,c){b="";if(0==a.s6)a=1==a.OC?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.OC)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Ii(z.Vl({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.s6)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Ii(z.Vl({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.s6){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign in to create a profile");b+=z.A(z.P({tb:!0,bc:!0,source:"highlight_tip",s:(0,z.O)(""+d),href:(0,z.M)(""+z.G(z.Vk(c)))},c))+" "+a}return(0,z.y)(b)},O$=function(a,b,c,d,e,g,k,l){z.R.call(this);this.ra=a;this.xa=a.get("butter-bar");this.bb=b;this.Ke=c;this.Rj=e;this.ue=a.get("quotes-data");this.tf=a.get("notes-data");this.pj=a.get("responses-data");this.jf=g;this.lZ=d;this.m_=(this.gG=k)?k.Si():null;this.Hf=this.Ic=null;this.Uj={};this.O$=!!z.gv();this.Q$=!!z.iv();this.Pz=this.O$&&this.Q$&&
z.FI(b);this.tq=null;this.WM=0;this.Pca=y2a(this.ue,this.Ke);this.Wv=l;this.Va(this.Bv());this.Naa=z.gv()?2:3},t3a=function(a){a.pb(".js-block").forEach(function(a){this.Pa(a,"mouseenter",this.pqa,this);this.Pa(a,"mouseleave",this.F0,this)},a)},u3a=function(a){a.pb(".js-note").forEach(function(a){this.Pa(a,"mouseenter",this.nqa,this);this.Pa(a,"mouseleave",this.F0,this)},a)},v3a=function(a,b){var c=a.query(".js-note-"+b);a.Uj[b]||(a.Uj[b]=new M$(a.ra,c.querySelector(".js-replyEditor"),a.bb.La(),b,
a.Ke),z.hB(a,a.Uj[b],"saving",a.Hta,a),z.hB(a,a.Uj[b],"save",a.Bta,a),z.hB(a,a.Uj[b],"fail",a.Asa,a));z.sd(c,"is-noteEditorVisible");a.Uj[b].focus()},w3a=function(a,b){var c=a.Uj[b];c&&(c.ib()&&c.dd(""),a=a.query(".js-note-"+b),z.vd(a,"is-noteEditorVisible"))},x3a=function(a,b,c){var d=J$(a.jf,a.Ke);if(d){var e=[];a.Wv&&(e=a.Wv.quotes.map(function(a){return a.Si()}));(0,z.Ab)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),d=z.Ua(d,b);if(this.Wv)var l=
a.getAttribute("name").split(" "),d=d&&(0,z.dd)(l,z.Ua.bind(null,e));z.xd(a,"is-selected",c&&d)},a)}},P$=function(a){return(a=z.Dw(a,function(a){return z.qd(a,"js-note-item")}))&&a.getAttribute("data-note-id")},y3a=function(a,b,c,d){b=new z.AH(b,300);b.Va(c);b.subscribe("dismiss",d,a);b.pa();return b},Q$=function(a){var b=a.jc(),c=a.wd();a=a.ye();1<b.length&&(a=b[0].Ga().length);var d=new z.my;d.Lp(b[0].getName());d.Fg(c);z.K(d,"endIndex",a);d.dd(b[0].Ga().substring(c,a));return d},R$=function(a,
b){b%=a.Naa;0>b&&(b=a.Naa-1);a.WM=b;(b=a.query(".js-highlightTip"))&&z.gA(b,s3a,{s6:a.WM,OC:a.Pca})},S$=function(a,b,c,d){z.R.call(this);this.Va(this.Bv(d));this.Db=a.get("dom-monitor");this.bb=b;this.V$=!b.Ya().dr()||b.Tb();this.kb=b.La();this.jf=c;this.ue=a.get("quotes-data");this.pj=a.get("responses-data");this.tf=a.get("notes-data");this.Dv=null;this.Bh={}},z3a=function(a,b){b.forEach(function(a){a&&T$(this,a)},a)},T$=function(a,b){if(!a.Dv)if(J$(a.jf,b)){var c=A3a(a,b),c=B3a(a,c),c=C3a(a,c),
c=D3a(a,c);a.Bh[b]=c;E3a(a,b)}else delete a.Bh[b]},F3a=function(a,b){if(!a.Dv){var c=a.Bh[b];if(c){var d=c.length,c=C3a(a,c),c=D3a(a,c);a.Bh[b]=c;d!=c.length?E3a(a,b):c.forEach(function(a){a.Ua&&a.offsetTop&&(a.Ua.style.top=a.offsetTop+"px")})}}},G3a=function(a,b,c){return z.Sa(a.Bh[b]||[],function(a){return a.Ua==c})},A3a=function(a,b){var c=[];F$(a.tf,b).Qg(function(a){var e=a.uB(),g;e?(g=this.tf.YQ(e),e=g.eb(),g=z.I(g,"endIndex")):(e=0,g=a.ib().length);c.push({anchor:b,startIndex:e,endIndex:g,
notes:[a],quotes:[],responses:[]})},a);if(a.V$)return c;(a.ue.tt[b]||[]).forEach(function(a){var e=H3a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);u$(a.pj,b).forEach(function(a){var e=s$(a);e&&(e=t$(e)&&t$(e).Gn())&&(e=H3a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},B3a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});b.forEach(function(a){var b=
z.Ra(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.zF(c[b],a):c.push(a)},a);return c},D3a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Ra(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.zF(c[b],a):c.push(a)}},a);return c},E3a=function(a,b){a.pb(".js-paragraphControl-"+b).forEach(z.ph);a.Bh[b]=a.Bh[b].map(function(a){var b=I3a(this,a),b=z.iA(J3a,b);b.style.top=a.offsetTop+"px";a.Ua=b;this.na().appendChild(a.Ua);
z.sd(b,"is-visible");return a},a)},I3a=function(a,b){var c=b.notes,d=b.responses,e=o$(a.ue,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,q=0,r=0,u=!1,v=!1,C={},J={},Q=z.fv().userId,N=a.bb.Ya().Nf().mb();c.forEach(function(a){var b=a.IH();b&&((a=z.I(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==Q&&l++,a.author.social&&a.author.social.isFollowing&&(C[a.author.userId]=a.author),J[a.author.userId]=!0)}),J[b.userId]=!0,b.userId==Q&&l++,b.userId==N?q++:r++,b.social&&b.social.isFollowing&&
(C[b.userId]=b))});e.forEach(function(a){a=a.user;J[a.userId]=!0;a.userId==Q&&(u=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});d.forEach(function(a){a=a.Nf();J[a.userId]=!0;a.userId==Q&&(v=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.kb,$A:b.anchor,MEa:k,zFa:g,fy:v,Xx:l,Xga:q,NEa:r,TWa:e.length,dy:u,Lfa:Object.keys(J).length,HCa:z.ob(C),OC:c.length}},H3a=function(a){var b=a.wd(),c=a.ye();1<a.paragraphs.length&&(c=
a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},C3a=function(a,b){var c=z.EA();return b.map(function(a){var b=this.jf.get(a.anchor),g=this.bb.Ri(b);if(!g)return a;var k;4==g.type&&(g.Ga()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.gEa))if(3==l.nodeType){var q=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=q.length}else if(l.nodeName in z.XS)k+=z.XS[l.nodeName].length;else for(q=
l.childNodes.length-1;0<=q;q--)b.push(l.childNodes[q]);k=l}g=z.HA(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},J3a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.$A)+' u-noUserSelect"\x3e',e=z.y,g;if(a.MEa||a.zFa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.$A)+'"\x3e';var k;k={};k=(0,z.y)(z.lm(z.D({name:"asteriskFilled",size:"19px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",q="",r=1==a.Xx?z.n("a note"):z.n("notes"),q=q+(""+r),q=z.E(q);1==a.Lfa&&(0<a.Xx||a.dy||a.fy)&&(0<a.Xx&&a.dy&&a.fy?(q=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):0<a.Xx&&a.fy?(q=z.n("responded and left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):0<a.Xx&&a.dy?(q=z.n("highlighted and left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):a.dy&&a.fy?(q=z.n("highlighted and responded"),l+=" "+q):a.dy?
(q=z.n("highlighted"),l+=" "+q):0<a.Xx?(q=z.n("left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):a.fy&&(q=z.n("responded"),l+=" "+q));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';q="";if(0<a.Xga&&0==a.NEa&&!a.dy&&!a.fy)c=1==a.Xga?z.n("Note to self"):z.n("Notes to self"),q+=c;else{r="";if(0<a.OC)var u=z.n("Top highlight"),r=r+u;q+=z.A(z.VR(z.D({social:a.HCa,isActive:0<a.Xx||a.dy||a.fy,Ai:a.Lfa,U3:!0,YEa:!0,nea:(0,z.O)(r)},a),c));q+=z.A(l)}q=(0,z.O)(q);k+=z.A(z.sCa(z.D({text:q},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},U$=function(a,b,c){z.R.call(this);this.ra=a;this.Ia=a.get("app");this.Toa=a.get("floating-components");this.Na=a.get("screen");this.rb=a.get("screen-service");this.Db=a.get("dom-monitor");this.bb=b;this.Pd=b.Pd;this.Vl=this.Pd.querySelector(".js-postField");this.dba=this.Na.na().querySelector(".js-notesPositionContainer");this.ue=a.get("quotes-data");this.tf=a.get("notes-data");this.tf.subscribe("new_note_list",this.Ysa,this);
this.pj=a.get("responses-data");this.Ul=null;this.jf=new d3a(this.Pd.querySelector(".js-notesSource"));this.xF=this.Bh=this.XO=null;this.Bh=new S$(a,b,this.jf,this.dba);this.track(this.Bh);this.xF=this.Bh.na();this.yf=this.OY=null;this.Le=c},W$=function(a,b){if(a.isActive()){var c=(b=b||a.OY)&&b.tR,d=b&&b.noteId;c&&(a.uw(c),d&&a.tf.pp(d,c)&&a.yf&&z.t(a.yf,function(){return V$(a,c,null,d)}));z.tka(a.Ia,"")}else a.OY=b||null},V$=function(a,b,c,d,e,g){var k={Hj:!0,M3:z.mA()};a.v_();c=new O$(a.ra,a.bb,
b,d||"",c||null,a.jf,e||null,g||null);c.subscribe("set-active-highlight",a.Xba,a);c.subscribe("reset-highlight",a.jwa,a);c.subscribe("close",a.v_,a);b=g&&g.Ua?g.Ua:a.jf.get(b);g=z.qsa(a.Toa);g.pn=b;b=g.RC(c);b.ZG=k;k=b.rU(a.fn.bind(a));k.LO=!0;a.Ul=k.pa()},K3a=function(a,b,c){var d=a.bb.Ri(J$(a.jf,b));if(d&&4!=d.type){z.kx(d,4);if(c){if(!$2a(c,d))return;z.ix(d,z.Tw(c.startIndex,c.endIndex,c.id))}c=a.bb.Tb();var e=a.bb.Ya();c={mode:c?"edit":"view",Dj:z.xx(e),media:null,Ll:null,sections:!0,yk:!1,vk:!1,
ql:!1,Jf:!1,postId:e.id};a.jf.get(b).innerHTML=z.Vx(d,z.Xr,c)}},L3a=function(a,b){var c=z.Zs();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Mf();var d=f3a(a.jf,b);if(!d)return null;a=(b=z.Dw(b,z.gE,d))&&a.bb.Ri(b);if(!b)return null;var d=z.JA(c,b,!0),e=z.JA(c,b,!1);return-1==d||-1==e?null:new a3a(c,b,new z.my({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ga().substring(d,e)}))},M3a=function(){},X$=function(a,b){z.R.call(this);this.Fh=b||H2a;this.Xa=a.get("screen-request");
this.va=null;this.S0=a.get("screen-view-state");this.ra=a;this.kca=this.U_=!1;this.FZ=this.Ic=null},Y$=function(a){z.fB.call(this);this.Ey=a},N3a=function(a,b,c){a=z.qa(a)?new z.ge(a):a;(a=X2a(a,b,c||{}))&&(new Y$(a)).focus()},O3a=function(a){this.oa=a.get("request");this.la=a.get("route-builder")},P3a=function(a,b){b=new z.Kk(b.authBaseUrl);return new z.ge(b.un(a))},Q3a=function(a,b,c){b.content=b.content.replace(/“/g,"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’");var d=String(a(b,null,
c)),e=Z$(d)-140;0<e&&(b.content=z.pj(b.content,b.content.length-e),d=String(a(b,null,c)));return d},Z$=function(a){var b=a.length;a=a.match(R3a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},$$=function(a){z.Yr.call(this);this.ra=a;this.jE=a.get("dialog");this.oa=a.get("request");this.la=a.get("route-builder");this.xa=a.get("butter-bar");this.eH=this.Ba=this.Lw=this.va=null;this.bN=!1},T3a=function(a){var b=a.Ba.query(".js-tweetEditor-image"),c=a.Ba.query(".js-tweetEditor-imageContainer"),
d=a.Ba.query(".js-tweetEditor-imageStatus");z.sd(c,"u-hide");var e=S3a(a);e.base64=!0;z.w(z.t(a.oa.post(z.hA(J2a),e,{aB:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.vd(c,"u-hide");z.sd(d,"u-hide");this.bN=!0},a),function(a){z.bB(a);z.gA(d,L2a)},a)},U3a=function(a,b){return 140>=Z$(b)?!0:(b=a.Ba.query(".js-tweetEditor-text"),(new z.uB(b,{name:"shimmy-shake",duration:400})).start(),a=a.Ba.query(".js-tweetEditor-error"),z.gA(a,P2a),!1)},S3a=function(a){var b=a.va,c=a.Lw.AGa;
a=a.Lw.zGa;var d=b.creator,e=b.approvedHomeCollection,g=z.Xr,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var q=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(q=e.tintColor);var r=null;e&&e.tintColor&&(r=z.UDa(e.tintColor),r=z.tw(r,.6).color);return new x$({content:c,altText:a,title:b.title,author:d&&d.name,date:z.kj(b.createdAt,g),authorAvatarId:d&&d.imageId,collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:q,
collectionHighlightColor:r,version:2})},V3a=function(a){this.oa=a.get("request");this.la=a.get("route-builder");this.ra=a};z.p(m$,z.L);z.f=m$.prototype;z.f.ba=function(){return""};z.f.ca=function(){return"Placement"};z.f.vg=function(){return z.I(this,"items")};z.f.Uc=z.h(433);z.f.wC=function(a){return z.K(this,"location",a)};z.f.Sd=z.h(480);z.f.Ub=function(a){return z.K(this,"index",a)};z.f.fa=function(){return m$.prototype};
z.f.ea={name:"Placement",ha:!1,fields:{items:{name:"items",g:function(){return z.MO},qa:z.T,h:1},location:{name:"location",g:function(){return z.FAa},h:2},index:{name:"index",g:z.V,h:3}},ia:{}};z.f.Sd=z.X(480,function(){return z.I(this,"index")});z.f.Uc=z.X(433,function(a){return z.K(this,"items",a)});z.m(p$,z.Te);p$.prototype.jk=function(a){var b={};z.gH(this,b,a.Nb(),"");return b};
p$.prototype.Jb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.Hj(g,k);if(!l)break;var q=l.g();if(l.qa()){var r=z.Cj(g,k)||[],u=e.shift(),v=Number(u);if(void 0===u||!Number.isInteger(v)||0>v)break;if(q.prototype instanceof z.wj)l=r[v],l||(l=new q,r[v]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;q=r2a(b[a],l);r[v]=q;z.K(g,k,r)}}else if(q.prototype instanceof z.wj)r=z.Cj(g,
k),r||(r=new q,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;q=r2a(b[a],l);z.K(g,k,q)}k=e.shift()}});return c};z.p(q$,z.Wj);z.f=q$.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.hR=z.h(631);z.f.fa=function(){return q$.prototype};z.f.ea={name:"PlacementsResponse",ha:!1,fields:{placements:{name:"placements",g:function(){return m$},qa:z.T,h:1}},ia:{}};z.p(r$,z.L);r$.prototype.ba=function(){return""};r$.prototype.ca=function(){return""};r$.prototype.fa=function(){return r$.prototype};
r$.prototype.ea={name:"PlacementsRequestQuery",ha:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.zF},h:1},slots:{name:"slots",g:function(){return z.ZF},qa:z.T,h:2}},ia:{}};z.yY.prototype.FT=z.X(646,function(a){a!=this.kN&&this.wb&&(this.wb.Yh.contentEditable=a);this.kN=a});z.nJ.prototype.J2=z.X(638,function(a){a=s$(a);if(!a)return null;a=t$(a)&&t$(a).Gn();return a?(a=a.jc())&&a.length?a[0].getName():null:null});z.FH.prototype.rU=z.X(637,function(a){this.fn=a;return this});
z.zJ.prototype.rU=z.X(636,function(a){this.fn=a;return this});q$.prototype.hR=z.X(631,function(){return z.I(this,"placements")});z.hH.prototype.hR=z.X(630,function(a,b){var c=this;a=t2a(u2a(new r$,a),b);a=(new p$).jk(a);var d=this.la.ka(z.Eta,{},a);return z.iH(this,d,function(){return z.t(c.oa.get(d,{background:!0}),function(a){a=c.Ha.Xb(q$,a);c.ya.Yb(a);return a})})});z.HB.prototype.pp=z.X(529,function(){return z.I(this,"note")});z.dH.prototype.pp=z.X(528,function(a){return this.oc("Note",a)});
z.ly.prototype.vx=z.X(505,function(){return z.I(this,"replyId")});z.HB.prototype.vx=z.X(504,function(){return z.I(this,"replyId")});z.jy.prototype.ny=z.X(503,function(a){return z.K(this,"highlight",a)});z.jy.prototype.YQ=z.X(502,function(){return z.I(this,"highlight")});z.jy.prototype.Pu=z.X(501,function(a){return z.K(this,"author",a)});z.ly.prototype.Pu=z.X(500,function(a){return z.K(this,"author",a)});z.jy.prototype.IH=z.X(499,function(){return z.I(this,"author")});
z.ly.prototype.IH=z.X(498,function(){return z.I(this,"author")});z.jy.prototype.uB=z.X(497,function(){return z.I(this,"highlightId")});z.jy.prototype.qy=z.X(496,function(a){return z.K(this,"state",a)});z.ly.prototype.qy=z.X(495,function(a){return z.K(this,"state",a)});z.zB.prototype.qy=z.X(494,function(a){return z.K(this,"state",a)});z.jy.prototype.wg=z.X(493,function(){return z.I(this,"noteId")});z.ly.prototype.wg=z.X(492,function(){return z.I(this,"noteId")});
z.HB.prototype.wg=z.X(491,function(){return z.I(this,"noteId")});z.Zv.prototype.Qu=z.X(485,function(a){return z.K(this,"authorId",a)});z.jy.prototype.Qu=z.X(484,function(a){return z.K(this,"authorId",a)});z.ly.prototype.Qu=z.X(483,function(a){return z.K(this,"authorId",a)});z.Vu.prototype.ke=z.X(400,function(){return z.I(this,"catalogId")});z.HM.prototype.ke=z.X(399,function(){return z.I(this,"catalogId")});z.zM.prototype.ke=z.X(398,function(){return z.I(this,"catalogId")});
z.xM.prototype.ke=z.X(397,function(){return z.I(this,"catalogId")});z.MO.prototype.ke=z.X(396,function(){return z.I(this,"catalogId")});z.bM.prototype.ke=z.X(395,function(){return z.I(this,"catalogId")});z.XN.prototype.ke=z.X(394,function(){return z.I(this,"catalogId")});z.WM.prototype.ke=z.X(393,function(){return z.I(this,"catalogId")});z.PN.prototype.ke=z.X(392,function(){return z.I(this,"catalogId")});z.ON.prototype.ke=z.X(391,function(){return z.I(this,"catalogId")});
z.NN.prototype.ke=z.X(390,function(){return z.I(this,"catalogId")});z.Zv.prototype.ke=z.X(389,function(){return z.I(this,"catalogId")});z.cP.prototype.ke=z.X(388,function(){return z.I(this,"catalogId")});z.HB.prototype.ke=z.X(387,function(){return z.I(this,"catalogId")});z.$J.prototype.ke=z.X(386,function(){return z.I(this,"catalogId")});z.Kt.prototype.iR=z.X(82,function(){return z.I(this,"point")});
v$.prototype.iR=function(){var a=window.document.body;return z.vh(a,this.fi.node)?this.fi:this.Jk&&z.vh(a,this.Jk)?z.zP(this.$N,this.Jk):this.Ke&&(a=z.Gw(this.Qoa,this.Ke))?z.zP(this.$N,a):null};z.p(w$,z.ls);w$.prototype.lJ=function(){if(!this.Yj)return null;var a=this.Yj.iR();if(!a)return null;var b=this.Yl.iR();return b?z.Ms(a.node,a.offset,b.node,b.offset):null};z.p(x$,z.L);z.f=x$.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.ib=function(){return z.I(this,"content")};
z.f.dd=function(a){return z.K(this,"content",a)};z.f.Gb=function(){return z.I(this,"title")};z.f.Vc=function(a){return z.K(this,"title",a)};z.f.IH=function(){return z.I(this,"author")};z.f.Pu=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.I(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Fb=function(){return z.I(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.IJ=function(a){return z.K(this,"template",a)};
z.f.oe=function(){return z.I(this,"subtitle")};z.f.Sf=function(a){return z.K(this,"subtitle",a)};z.f.fa=function(){return x$.prototype};
z.f.ea={name:"TextshotInfo",ha:!1,fields:{content:{name:"content",g:z.U,h:1},altText:{name:"altText",g:z.U,h:2},title:{name:"title",g:z.U,h:3},author:{name:"author",g:z.U,h:4},date:{name:"date",g:z.U,h:5},authorAvatarId:{name:"authorAvatarId",g:z.U,h:6},collection:{name:"collection",g:z.U,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.U,h:8},collectionLogoId:{name:"collectionLogoId",g:z.U,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.U,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.U,h:11},version:{name:"version",g:z.V,h:12},base64:{name:"base64",g:z.hK,h:13},template:{name:"template",g:z.U,h:14},mainStat:{name:"mainStat",g:z.U,h:15},mainStatTitle:{name:"mainStatTitle",g:z.U,h:16},subtitle:{name:"subtitle",g:z.U,h:17},icon:{name:"icon",g:z.U,h:18},imgKey:{name:"imgKey",g:z.U,h:19}},ia:{}};z.p(z$,z.R);z.f=z$.prototype;z.f.nk=function(){return this.dm.nk()};
z.f.ma=function(){z$.ua.ma.call(this);z.hB(this,this.GX,"data-redirect-type-quote",this.isa,this);this.Pa(this.Pd,"click",this.Ov,this);z.GI(this.bb)&&z.kA()&&this.Pa(this.Pd,"mouseover",this.Hpa,this);this.bb.Ya().dr()&&!this.bb.Tb()&&z.w(this.ue.load(this.bb.La()),z.bB);var a=this.nk();a&&(z.hB(this,a,"quote",this.Cpa,this),z.hB(this,a,"quote-respond",this.Dpa,this),z.hB(this,a,"show",this.H0,this),z.hB(this,a,"hide",this.Bsa,this))};
z.f.isa=function(a){var b=z.sI(this.dm,this.nk().Iw);b&&(a.url=new z.ge(this.la.ka(z.Mwa,{postId:this.bb.La()},{paragraphs:JSON.stringify([b.Bx.Jb().Nb()]),startOffset:b.start,endOffset:b.end})))};z.f.Ov=function(a){z.Dw(a.target,function(a){if(a===this.Pd)return!0;var c=z.qE(a);if(3==c)return!0;if(7==c){if(c=T2a(this,a))if(A$(this,c),z.kA())C$(this,c);else{var d=new z.gG;R2a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.Hpa=function(a){z.Dw(a.target,function(a){if(a===this.Pd)return!0;var c=z.qE(a);if(3==c)return!0;if(7==c){c=z.Zs();if(!(c&&!c.isCollapsed()||this.nk()&&this.nk().Am())&&(c=T2a(this,a))){var d=this.Pd.querySelector('.markup--quote[name~\x3d"'+c.Si()+'"]');a=new z.AH(a,100);R2a(this,c,d,a);A$(this,c)}return!0}return!1}.bind(this))};
z.f.H0=function(){var a=z.Zs();a&&!a.isCollapsed()&&A$(this,null);z.GI(this.bb)&&(a=z.sI(this.dm,this.nk().Iw))&&(a=z.nqa(this.ue,a.Bx,a.start,a.end),z.xd(this.nk().Ra().querySelector(".js-highlightMenuQuoteButton"),"is-active",!!a))};z.f.Bsa=function(){this.Wo&&A$(this,null)};
z.f.Cpa=function(){if(z.GI(this.bb)){var a=z.nI(this.nk());if(a){var b=a.range,c=a.VDa,d=z.qd(this.nk().Ra().querySelector(".js-highlightMenuQuoteButton"),"is-active"),a=z.sI(this.dm,b);z.w(z.t(this.ue.toggle(a.Bx,a.start,a.end,!c),function(a){z.YDa();d?z.pI(this.nk()):C$(this,a);var b=c?"selection_menu":"quote_click_menu";D$(this,a.Si(),!d,b)},this),z.bB)}}};
z.f.Dpa=function(){if(z.GI(this.bb)&&z.Xr.supportsEdit){var a=z.nI(this.nk());if(a){var b=z.sI(this.dm,a.range);z.w(z.t(this.ue.create(b.Bx,b.start,b.end,1,!0),function(a){D$(this,a.Si(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.Bx.name)},this),z.bB)}}};
z.f.Opa=function(a){var b=this.Wo,c=B$(this,b),d=b.wd(),e=b.ye(),b=a.query(".js-quoteAttributions-pileOn"),g=z.qd(b,"is-active");z.w(z.t(this.ue.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.yd(l,"is-active");if(l=z.jI(this.ue,c,d,e)){var q=Q2a(this,l),r=a.query(".js-quoteAttributions-info");z.gA(r,D2a,q)}else a.Rc();!g&&z.kA()&&(a.Rc(),C$(this,l));l=z.kA()?"quote_hover":"quote_click_mobile";D$(this,b.Si(),!g,l)},this),z.bB)};
z.f.Ppa=function(){if(z.GI(this.bb)&&z.Xr.supportsEdit){var a=B$(this,this.Wo),b=this.Wo.wd(),c=this.Wo.ye();z.w(z.t(this.ue.create(a,b,c,1,!0),function(b){D$(this,b.Si(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.bB)}};z.f.Qpa=function(){var a=V2a(this,this.Wo);a&&z.xqa(this.dm,a)};
z.f.Nba=function(){var a=new w$(this.Pd),b=this.ue.tt,c=Object.keys(b).concat(this.p9);z.cb(c);c.forEach(function(a){var c=b[a]||[],g=this.bb;if(g=(a=g.Pd&&z.Gw(g.Pd,a))&&this.bb.Ri(a))C2a(g,c),a.innerHTML=z.Vx(g,z.Xr,z.Iqa(this.bb)),z.zsa(this.ova,a)},this);this.p9=Object.keys(b);(a=a.restore())&&a.select()};z.p(E$,z.fB);z.f=E$.prototype;
z.f.load=function(a){if(!z.gv())return z.hd([]);this.kb=a;this.xh||(this.xh=z.w(z.t(this.gn.get(this.la.ka(z.Ewa,{postId:a}),{background:!0}),this.mva,this),z.bB));return this.xh.Xc()};z.f.Bp=function(){return this.m9};z.f.pk=function(){return this.jba};z.f.YQ=function(a){return this.D$[a]||null};z.f.pp=function(a,b){return z.gQ(F$(this,b),a)};z.f.ny=function(a,b){this.D$[a]=b};z.f.La=function(){return this.kb};
z.f.mva=function(a){var b=a.references.User;this.jba=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var q=g[l],r=q.authorId||null;q.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=F$(this,g);e=z.ky(e);g.add(z.bF(this.ya,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.ny(a[b].id,z.Dt.Jb(z.my,a[b]));this.m9=!0};z.m(I$,z.R);I$.prototype.ma=function(){var a=this;z.R.prototype.ma.call(this);z.t(this.Xa.hR(this.PO,this.Zua),function(b){b.placements&&b.placements.forEach(a.Aqa,a)})};
I$.prototype.Aqa=function(a){if(this.isActive()){var b=null;switch(a.location){case 1:b=this.Na.query(".js-postFooterPlacements");if(!b)break;z.gA(b,z.lS,{items:a.items,context:9});z.S(b).aa("show-more-recommendations",this.Lxa,this);break;case 2:b=this.Na.query(".js-readNextMetabarRight");if(!b)break;z.gA(b,z.lS,{items:a.items,context:2});break;case 6:(b=this.Na.query(".js-postPromotionWrapper"))&&z.gA(b,z.lS,{items:a.items,context:2})}b&&b3a(this,b)}};
I$.prototype.Lxa=function(a){z.OB(z.pAa,{});var b=this.Na.query(".js-moreRecommendations");b&&(z.Jw(b),z.Iw(a.target))};c3a.prototype.qQ=function(a,b,c){return new z$(a,b,c)};d3a.prototype.get=function(a){return J$(this,a)};z.p(K$,z.yY);z.f=K$.prototype;z.f.uG=!1;z.f.Mz="";z.f.vG=0;z.f.ym=z.T;z.f.wg=function(){return this.lZ};z.f.save=function(){this.ib().length<=this.cm&&this.dl()};z.f.Ib=function(){(0,window.clearTimeout)(this.vG);K$.ua.Ib.call(this)};
z.f.ma=function(){function a(a){a.stopPropagation()}K$.ua.ma.call(this);this.Mz=this.ib();this.dd(this.Mz);this.Uw(13,this.qZ,this);this.Uw(27,this.rZ,this);this.wb.Pa("blur",this.pZ,!1,this);var b=this.wb.Ra();z.wA(b,"keydown",a);z.wA(b,"keyup",a);z.wA(b,"keypress",a)};z.f.Y4=function(a){return a};
z.f.dl=function(){if(this.isEnabled()){var a=this.ib().trim();if(a){this.FT(!1);var b=this.gfa(),a=this.ffa(a);this.za("saving",a);z.Yc(z.w(z.t(this.gn.post(b,a.Nb()),this.bta,this),this.$sa.bind(this,a)),this.FT.bind(this,!0))}}};z.f.bta=function(a){this.za("save",this.Y4(a.value))};z.f.$sa=function(a,b){this.za("fail",a);this.Ba.error(g3a());z.bB(b)};z.f.qZ=function(a){if(this.Et&&z.mZ(this.Et))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.rZ=function(a){if(this.Et&&z.mZ(this.Et))return!1;a.preventDefault();this.dd(this.Mz);this.za("cancel");return!1};z.f.pZ=function(){this.uG&&(this.ib().length>=this.cm?(0,window.confirm)(this.ifa())?(this.dd(this.Mz),this.za("cancel")):this.focus():this.vG=(0,window.setTimeout)(this.dl.bind(this),100))};z.p(L$,K$);z.f=L$.prototype;z.f.PV=null;z.f.E8=null;z.f.QV=null;z.f.Rj=null;z.f.bY=null;z.f.aY=null;z.f.C$=null;z.f.ny=function(a){this.Rj=a;this.bY=a.startIndex;this.aY=a.endIndex;this.C$=a.content;return this};z.f.ifa=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.Y4=function(a){var b=z.eA();a=z.ky(a).Pu(b).Qu(b.mb());this.Rj&&a.uB()&&this.tf.ny(a.uB(),this.Rj);var b=this.tf,c;c=z.bF(b.ya,a);F$(b,c.je()).add(c);return a};
z.f.gfa=function(){return this.wg()?this.la.ka(z.Fwa,{postId:this.kb,noteId:this.wg()}):this.la.ka(z.Dwa,{postId:this.kb})};z.f.ffa=function(a){var b=z.eA();a=(new z.jy({content:a,anchor:this.PV,anchorContent:this.E8,anchorImage:this.QV?this.QV.Nb():null,replies:[],createdAt:Date.now()})).Pu(b);null!=this.bY&&null!=this.aY&&(b=new z.my({anchor:this.PV,startIndex:this.bY,endIndex:this.aY,content:this.C$}),a.ny(b));return a};z.p(M$,K$);M$.prototype.ifa=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};M$.prototype.Y4=function(a){var b=z.eA();a=z.vha(a).Pu(b).Qu(b.mb());z.I(this.tf.pp(a.wg(),this.Ke),"replies").push(a);return a};M$.prototype.gfa=function(){return this.Jba?this.la.ka(z.Iwa,{postId:this.kb,noteId:this.wg(),replyId:this.Jba}):this.la.ka(z.Hwa,{postId:this.kb,noteId:this.wg()})};
M$.prototype.ffa=function(a){var b=z.eA();return(new z.ly({replyId:"",postId:this.kb,noteId:this.wg(),content:a,createdAt:Date.now()})).Pu(b)};z.p(O$,z.R);z.f=O$.prototype;
z.f.ma=function(){O$.ua.ma.call(this);z.S(this.na()).aa("show-note-editor",this.Z_,this).aa("hide-note-editor",this.YX.bind(this,!0)).aa("show-reply-editor",this.Yxa,this).aa("hide-reply-editor",this.lqa,this).aa("save-note",this.Awa,this).aa("save-reply",this.Cwa,this).aa("highlight-quote",this.oqa,this).aa("dismiss-note",this.t9.bind(this,!0),this).aa("delete-note",this.t9.bind(this,!1),this).aa("delete-reply",this.Zna,this).aa("previous-highlight-tip",this.kva,this).aa("next-highlight-tip",this.Nra,
this);u3a(this);this.pj&&n$(this.pj)&&(t3a(this),z.hB(this,n$(this.pj),"add",this.Zsa,this));if(this.m_&&this.O$&&this.Q$){var a=this.query(".js-inlineNewPostControl"),b=this.m_,c=this.bb.La(),d=new z.BU(this.ra);d.vJ("web-inline-quote-responses");d.Va(a);d.lE=!0;d.QW=!0;d.NW=!0;d.IJ(E2a);d.Lz=b;d.zJ(c);z.CU(d,!0);this.Ic=d;this.Ic.pa();a=Q$(this.gG);this.za("set-active-highlight",this.Ke,a)}this.Rj&&(this.Z_(),this.Hf&&this.Hf.focus());R$(this,0)};
z.f.Aa=function(){this.tq&&this.tq.V1();(this.Rj||this.gG)&&this.za("reset-highlight",this.Ke,null);O$.ua.Aa.call(this)};z.f.Ib=function(){z.WB(this.na());z.ph(this.na());z.$r(this.Ic);z.$r(this.Hf);z.$r(this.tq);z.as(z.ob(this.Uj));this.tq=this.Uj=this.Hf=this.Ic=null;O$.ua.Ib.call(this)};z.f.Ln=function(){if(this.Hf&&this.Hf.ib())return!0;for(var a=z.ob(this.Uj),b=0;b<a.length;b++)if(a[b]&&a[b].ib())return!0;return this.Ic&&!this.Ic.isDismissable()?!0:!1};
z.f.Bv=function(){var a=[],b=[],c=[],d=this.Pz&&(this.Rj||this.gG);d||(this.Wv?(a=this.ue?o$(this.ue,this.Wv.quotes):[],b=this.Wv.notes,c=this.Wv.responses):(b=this.tf?z.kF(F$(this.tf,this.Ke)):[],this.lZ||(this.ue?(a=this.ue,a=o$(a,a.tt[this.Ke]||[])):a=[],c=this.pj?u$(this.pj,this.Ke):[])));return z.iA(q3a,{post:this.bb.Ya(),quotes:a,notes:b,responses:c,G6:!!this.m_,OT:d,LJ:this.Pz,OC:this.Pca,OEa:z.FI(this.bb)})};
z.f.Zsa=function(){var a=this.query(".js-postList"),b=z.iA(p3a,{responses:u$(this.pj,this.Ke)});z.qh(b,a);t3a(this)};
z.f.Z_=function(){if(this.Pz){if(!this.Hf){var a=this.query(".js-noteEditor"),b=z.hA(n3a),a=this.Hf=new L$(this.ra,a,this.bb.La(),null,b),b=this.Ke,c=this.bb.Ri(this.jf.get(this.Ke)),d=c.Ga(),c=4==c.type?c.le():null;a.PV=b;a.E8=d;a.QV=c;(a=this.Rj)&&this.Hf.ny(a);z.hB(this,this.Hf,"saving",this.Gta,this);z.hB(this,this.Hf,"fail",this.zsa,this);z.hB(this,this.Hf,"save",this.Ata,this)}z.sd(this.query(".js-noteActions"),"is-noteEditorVisible");this.Hf&&this.Hf.focus()}};z.f.Awa=function(){this.Hf&&this.Hf.save()};
z.f.Gta=function(a){this.Hf.dd("");var b=this.query(".js-notesList");a={note:a,post:this.bb.Ya(),OT:this.Pz,LJ:this.Pz};a=z.iA(N$,a);b.appendChild(a);z.vd(b,"is-empty");u3a(this);this.YX()};z.f.Ata=function(a){var b=this.query(".js-notesList").lastChild;a=a.wg();z.sd(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};z.f.zsa=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.sd(a,"is-empty");this.Z_()};
z.f.YX=function(a){a?this.za("close"):this.Hf&&(this.Hf.ib()&&this.Hf.dd(""),z.vd(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.Yxa=function(a){(a=P$(a.target))&&this.Pz&&v3a(this,a)};z.f.Cwa=function(a){a=P$(a.target);(a=this.Uj[a])&&a.save()};
z.f.Hta=function(a){var b=a.wg();this.Uj[b]&&this.Uj[b].dd("");var c=this.tf.pp(b,this.Ke).author.userId==a.author.userId,d=this.query(".js-note-"+a.wg()+" .js-repliesList");a={note:a,post:this.bb.Ya(),iga:c};a=z.iA(N$,a);d.appendChild(a);z.vd(d,"is-empty");w3a(this,b)};z.f.Bta=function(a){var b=this.query(".js-note-"+a.wg()).querySelector(".js-repliesList").lastChild;a=a.vx();z.sd(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Asa=function(a){var b=this.query(".js-note-"+a.wg()+" .js-repliesList");b.removeChild(b.lastChild);z.sd(b,"is-empty");v3a(this,a.wg())};z.f.lqa=function(a){(a=P$(a.target))&&w3a(this,a)};z.f.oqa=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=J$(this.jf,this.Ke);c&&(this.tq&&this.tq.V1(),this.tq=y3a(this,c,a,function(){x3a(this,b,!1);z.$r(this.tq);this.tq=null}),x3a(this,b,!0))};
z.f.nqa=function(a){var b=J$(this.jf,this.Ke);(a=this.tf.pp(a.target.getAttribute("data-note-id"),this.Ke))&&b&&(b=(b=a.uB())?this.tf.YQ(b):null,this.za("set-active-highlight",this.Ke,b))};z.f.pqa=function(a){var b=J$(this.jf,this.Ke),c;c=this.pj;a=a.target.getAttribute("data-post-id");c=n$(c)?z.gQ(n$(c),a):null;b&&c&&(b=s$(c))&&(b=t$(b)&&t$(b).Gn())&&(c=b.jc())&&c.length&&(b=Q$(b),this.za("set-active-highlight",this.Ke,b))};
z.f.F0=function(){var a=null;this.gG&&(a=Q$(this.gG));this.Rj&&(a=this.Rj);this.za("reset-highlight",this.Ke,a)};
z.f.t9=function(a,b){b=b.value;var c=this.tf.pp(b,this.Ke),d=this.query(".js-note-"+b);if(c&&d){z.Iw(d);this.F0();this.pb(".js-note-item").every(function(a){return z.qd(a,"u-hide")})&&this.YX(!0);var e=G$(this.tf,c,"HIDDEN");z.w(e.ul,function(b){this.xa.pa(a?h3a():i3a(),"error");e.mJ();z.Jw(d);(400>b.status||499<b.status)&&G$(this.tf,c,"NEW")},this);z.t(this.xa.pa(a?k3a():l3a(),{type:"success",PC:!0}),function(){this.xa.Rc();e.mJ();G$(this.tf,c,"NEW");z.Jw(d)},this)}};
z.f.Zna=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=P$(a.target);if(d&&c){z.Iw(c);var e=H$(this.tf,b,d,this.bb.La(),this.Ke,"HIDDEN");z.w(e.ul,function(){this.xa.pa(j3a(),"error");e.mJ();z.Jw(c);H$(this.tf,b,d,this.bb.La(),this.Ke,"")},this);z.t(this.xa.pa(m3a(),{type:"success",PC:!0}),function(){this.xa.Rc();e.mJ();H$(this.tf,b,d,this.bb.La(),this.Ke,"");z.Jw(c)},this)}};z.f.kva=function(){R$(this,this.WM-1)};z.f.Nra=function(){R$(this,this.WM+1)};z.p(S$,z.R);z.f=S$.prototype;z.f.ma=function(){S$.ua.ma.call(this);var a=[];z.FI(this.bb)&&a.push(this.tf.load(this.kb));this.V$||(a.push(this.ue.load(this.kb)),a.push(this.pj.load(this.kb)));this.Dv=z.t(z.t(z.t(z.wT(a),function(){this.Dv=null},this),this.Mr,this),this.Uma,this);z.hB(this,this.Db,"resize-end",this.gg,this)};z.f.Aa=function(){this.Dv&&this.Dv.cancel();S$.ua.Aa.call(this)};z.f.Ib=function(){this.Dv=null;S$.ua.Ib.call(this)};z.f.Mr=function(){e3a(this.jf,function(a,b){T$(this,b)},this)};
z.f.gg=function(){e3a(this.jf,function(a,b){F3a(this,b)},this)};z.f.Uma=function(){var a=this.ue.Mo;z.hB(this,a,"add",this.Uaa,this);z.hB(this,a,"remove",this.Uaa,this);(a=n$(this.pj))&&z.hB(this,a,"add",this.xta,this)};z.f.Uaa=function(a){z3a(this,Object.keys(z.rqa(this.ue,a instanceof Array?a:[a])))};z.f.xta=function(a){z3a(this,(a instanceof Array?a:[a]).map(this.pj.J2,this.pj))};z.f.Bv=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};
z.f.zF=function(a,b){z.wb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.p(U$,z.R);z.f=U$.prototype;
z.f.ma=function(){U$.ua.ma.call(this);this.Pa(this.Na.na(),"click",this.rra,this,!0);z.S(this.xF).aa("select-anchor",this.Kta,this);var a=this.bb.Ya();if(a.dr()&&!this.bb.Tb()){var b=z.Pu(a),b=2==a.visibility&&b&&!z.I(b.gu(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.w(this.pj.load(this.bb.La(),"best"),z.bB);z.w(this.ue.load(this.bb.La()),z.bB)}a.gu().HH()&&(this.YN=z.t(this.tf.load(this.bb.La()),this.cta,this));this.OY&&W$(this,null);z.hB(this,this.rb,"historyUpdate",function(){W$(this,
z.uI())},this);this.Le&&z.hB(this,this.Le,"highlight",this.ata,this)};z.f.Ib=function(){z.$r(this.Bh);this.Bh=null;z.$r(this.Ul);this.Ul=null;this.xF&&z.S(this.xF).clear("select-anchor");this.YN&&this.YN.cancel();this.YN=null;U$.ua.Ib.call(this)};z.f.UEa=function(a,b){V$(this,b,null,null,a)};z.f.OGa=function(){this.Bh&&this.Bh.gg()};z.f.Ln=function(){if(!this.Ul)return!1;var a=this.Ul.ib();return a?a.Ln():!1};z.f.Ysa=function(a){a.subscribe("add",this.Xca,this);a.subscribe("remove",this.Xca,this)};
z.f.Xca=function(a){(z.oa(a)?a:[a]).forEach(function(a){T$(this.Bh,a.je())},this)};z.f.cta=function(){var a=(0,z.Ja)();this.YN=null;W$(this,z.uI());this.Pa(this.Vl,z.HK,this.yZ,this);z.DC("notes.renderMarkers",(0,z.Ja)()-a)};z.f.yZ=function(a){(a=a.target.getAttribute("name"))&&J$(this.jf,a)&&F3a(this.Bh,a)};z.f.ata=function(){if(this.Le){var a=L3a(this,this.Le.Iw);z.pI(this.Le);a&&(a=a.highlight,this.Xba(a.anchor,a),V$(this,a.anchor,a))}};
z.f.rra=function(a){if(this.Ul){var b=a.target;if(!z.vh(this.Ul.na(),b)){var c=this.Ul.ib(),d;if(!(d=!c)){a:if(c.Hf&&c.Hf.ib())c=!0;else{d=z.ob(c.Uj);for(var e=0;e<d.length;e++)if(d[e]&&d[e].ib()){c=!0;break a}c=c.Ic&&!c.Ic.Wi()?!0:!1}d=!c}d&&(c=this.Ul&&this.Ul.pn,d="select-anchor"==b.getAttribute("data-action"),this.v_(),c&&d&&z.vh(c,b)&&a.stopPropagation())}}};
z.f.fn=function(a){if(!z.mA()){var b=a.pn,c=z.HA(b);a.zl();a=a.na();var d=z.HA(a),e=window.innerHeight,g=window.innerWidth,k=this.Na.query(".js-metabar"),l=0;k&&(l=z.HA(k).height);d.height>=e-l?Y2a(a):(z.DA(b),b=c.top+d.height>=e?z.EA().top+e-d.height-10:z.DA(b),c=z.HA(this.xF).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.v_=function(){z.$r(this.Ul);this.Ul=null};
z.f.Kta=function(a){var b=z.Dw(a.target,function(a){return z.qd(a,"js-paragraphControl")},this.dba),b=G3a(this.Bh,a.value,b);V$(this,a.value,null,null,null,b)};z.f.Xba=function(a,b){if(this.bb.Tb()){var c=z.Zs();this.XO=(c=c&&f3a(this.jf,c.Mf()))&&new w$(c)}K3a(this,a,b)};z.f.jwa=function(a,b){K3a(this,a,b);this.bb.Tb()&&this.XO&&(a=this.XO.restore())&&a.select();this.XO=null};
z.f.uw=function(a){if(this.jf&&(a=J$(this.jf,a))){a=Math.max(z.DA(a),0);var b=window.document.body;this.yf&&this.yf.cancel();this.yf=new z.nA(b,"scrollTop",600,a)}};M3a.prototype.qQ=function(a,b,c){return new U$(a,b,c)};z.m(X$,z.R);z.f=X$.prototype;z.f.Dc=function(a){this.va=a};z.f.IJ=function(a){this.Fh=a};z.f.WFa=function(a){this.U_=a};z.f.XFa=function(a){this.kca=a};
z.f.ma=function(){this.na()?(z.R.prototype.ma.call(this),z.S(this.na()).aa("show-responses-stream-editor",this.Vta,this).aa("show-other-responses",this.qca,this),z.gA(this.na(),this.Fh,{post:this.va}),this.va.dr()&&z.w(z.t(z.t(z.t(B2a(this.Xa,this.va.xb(),"best"),this.Gba.bind(this,"best")),this.Rva,this),function(){this.S0.c6&&this.qca()},this),z.bB)):z.bB("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Aa=function(){z.S(this.na()).clear("show-other-responses");z.R.prototype.Aa.call(this)};
z.f.Gba=function(a,b){this.isActive()&&(b=b.Hd,"best"==a?(a=this.query(".js-responsesStream"),z.hB(this,b,"add",this.waa.bind(this,b)),this.waa(b)):a=this.query(".js-responsesStreamOther"),b&&(z.iv()||0<b.Oe())&&a&&(z.gA(a,z.lS,{items:z.kF(b),context:2}),b=new z.bV(this.ra,b),b.Va(a),b.md(2),this.track(b),z.Jw(this.query(".js-responsesStreamWrapper"))),this.kca&&(a=z.DA(a),z.AA(window.document.body,0,a)))};
z.f.Rva=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.iv()?a?(this.Ic=z.CU(v2a((new z.BU(this.ra)).vJ("web-inline-post-response").zJ(this.va.xb()),z.fA(z.Ok,{post:this.va,wT:!0})),this.U_).Va(a),this.track(this.Ic)):b&&this.U_&&(a=z.CA(b),b=z.DA(b),z.AA(a,0,b)):b&&z.sd(b,"u-hide")};
z.f.qca=function(){this.FZ||(this.FZ=z.Yc(z.t(z.t(B2a(this.Xa,this.va.xb(),"other"),this.Gba.bind(this,"other")),function(){z.Iw(this.query(".js-showOtherResponses"));this.S0.c6=!0},this),function(){this.FZ=null},this))};z.f.waa=function(a){(a=a.Xk)&&a.next&&"other"==a.next.filter&&!this.S0.c6&&(z.Jw(this.query(".js-responsesStreamWrapper")),z.Jw(this.query(".js-showOtherResponses")))};z.f.hx=function(){this.Ic&&(z.jT(this.Ic.na(),new z.et(60,0,200,0)),this.Ic.hx())};
z.f.Vta=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.KS(a)&&(z.Jw(a),z.Iw(b),this.hx())};z.p(Y$,z.fB);Y$.prototype.focus=function(){this.isActive&&this.Ey.focus()};Y$.prototype.close=function(){this.Ey&&!this.Ey.closed&&this.Ey.close();this.za("close");this.Wf()};Y$.prototype.isActive=function(){return this.Ey?!this.Ey.closed:!1};Y$.prototype.Ta=function(){this.Ey=null;Y$.ua.Ta.call(this)};z.f=O3a.prototype;z.f.BC=function(a,b,c){var d;d=z.Xr;var e=new z.Kk(z.Wr(d)),e=new z.ge(e.un(a));d=y$(e,d);this.cw(d);z.OB(z.sL,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.V5=function(a){var b;b=z.Xr;var c=new z.Kk(z.Wr(b));a=new z.ge(c.ka(z.Az,{catalogSlug:a.ke(),username:a.Nf().rk()}));b=y$(a,b);this.cw(b)};z.f.W5=function(a){var b;b=z.Xr;var c=new z.Kk(z.Wr(b));a=new z.ge(c.ka(z.iz,{sequenceSlug:a.ld()}));b=y$(a,b);this.cw(b)};
z.f.E2=function(){var a=this.la.ka(z.jwa);return this.oa.get(a)};z.f.cw=function(a){N3a(a,"facebook-share",{width:550,height:320})};var R3a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;z.p($$,z.Yr);
$$.prototype.open=function(a,b){this.va=a;this.Lw=b;this.Ba=this.jE.open({bodyHtml:z.fA(M2a,this.Lw),type:"tweet"},!0);a=this.Ba.query(".js-tweetEditor-text");b=this.ra;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.eH=new z.O_(b,a,c(d),!0);a=new z.k_(140,!0);a.f9=Z$;this.eH.$a(a);a=Q3a(I2a,this.Lw,z.Xr);this.eH.dd(a);this.eH.focus();T3a(this);z.S(this.Ba.kc).aa("remove-textshot",this.bca.bind(this,!1),this).aa("add-textshot",this.bca.bind(this,!0),this).aa("toggle-expand-image",this.Uya,
this);this.Ba.subscribe("submit",this.Fza.bind(this))};$$.prototype.Fza=function(){var a=this.eH.ib();if(U3a(this,a)){var b=this.bN?S3a(this):null;z.w(z.t(this.oa.post(this.la.ka(z.hwa),{tweet:a,textshotInfo:b}),function(a){a=z.hA(K2a,{id:a.value});a=z.fA(O2a,{JGa:a});this.xa.pa(a,{type:"success",Rp:1E4})},this),function(a){z.bB(a);this.xa.pa(N2a(),"error")},this);z.xC(z.Qya,{postId:this.va.id,type:this.Lw.shareType,source:this.Lw.bGa,dest:"twitter",style:this.bN?"textshot":null});this.Ba.close()}};
$$.prototype.bca=function(a){this.bN=a;z.xd(this.Ba.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.xd(this.Ba.query(".js-tweetEditor-addTextshot"),"u-hide",a)};$$.prototype.Uya=function(){var a=this.Ba.query(".js-tweetEditor-image");z.yd(a,"tweetEditor-image--expanded")};z.f=V3a.prototype;z.f.aGa=function(a,b){var c=z.fv(),d=a.creator||{},e=A2a(b),g=z2a(b),k=P3a(a,z.Xr);(b=Z2a(b.G2()))&&z.le(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,AGa:e,zGa:g,shareType:"highlight",bGa:"highlight_menu"};z.w(z.t(this.ra.load("tweet-dialog"),function(b){b.open(a,l)}),z.bB);z.xC(z.sL,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.BC=function(a,b,c,d,e){var g=z.fv().userId,k="highlight"==c?I2a:z.Mqa,l=z.Xr,q=a.creator||{};b={content:b,name:q.name||"",username:q.username||"",twitterScreenName:q.twitterScreenName||"",Eda:q.userId==g,url:P3a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):Q3a(k,b,l);k=new z.ge("https://twitter.com/intent/tweet");z.xe(k,"text",d);this.cw(k);z.OB(z.sL,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.V5=function(a){var b=z.Xr,c=new z.Kk(z.Wr(b)),c=(new z.ge(c.ka(z.Az,{catalogSlug:a.ke(),username:a.Nf().rk()}))).toString();a=z.B(""+z.Vo(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.KI({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.ge("https://twitter.com/intent/tweet");z.xe(b,"text",a);this.cw(b)};
z.f.W5=function(a){var b=new z.Kk(z.Wr(z.Xr)),b=(new z.ge(b.ka(z.iz,{sequenceSlug:a.ld()}))).toString();a=z.B(""+z.Vo(String(a.title))+" "+(""+b));b=new z.ge("https://twitter.com/intent/tweet");z.xe(b,"text",a);this.cw(b)};z.f.cw=function(a){N3a(a,"twitter-share",{width:670,height:420})};var W3a=z.gC,X3a=W3a.Ca();X3a.scope("screen").add("quotes",c3a).add("quote-responses",M3a).add("responses-stream-control",X$).add("notes-data",E$);z.jC(X3a.scope("app"),"PlacementsControl",I$).add("twitter",V3a).add("facebook",O3a).add("tweet-dialog",$$);z.hQ(W3a,"notes");}).call(this, _mdm);
